export const ACQUIRE = {
  SCORE_WEIGHT: {
    RAMPART_COUNT: 1,
    FRANCHISES_INSIDE_PERIMETER: 1,
    SWAMP_COUNT: 1,
    MINERAL_TYPE: 2,
    REMOTE_COUNT: 1,
    DISTANCE: 3
  },
  MINERAL_PRIORITIES: [
    RESOURCE_CATALYST,
    RESOURCE_UTRIUM,
    RESOURCE_KEANIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN
  ] as MineralConstant[]
};
