type Stamp = (BuildableStructureConstant|undefined)[][]

export const HQ_STAMP: Stamp = [
  [STRUCTURE_STORAGE,  STRUCTURE_NUKER,   STRUCTURE_EXTENSION  ],
  [STRUCTURE_ROAD,     STRUCTURE_ROAD,    STRUCTURE_LINK       ],
  [STRUCTURE_TERMINAL, STRUCTURE_FACTORY, STRUCTURE_POWER_SPAWN],
]

export const LABS_STAMP: Stamp = [
  [STRUCTURE_ROAD, STRUCTURE_LAB,  STRUCTURE_LAB,  undefined     ],
  [STRUCTURE_LAB,  STRUCTURE_ROAD, STRUCTURE_LAB,  STRUCTURE_LAB ],
  [STRUCTURE_LAB,  STRUCTURE_LAB,  STRUCTURE_ROAD, STRUCTURE_LAB ],
  [undefined,      STRUCTURE_LAB,  STRUCTURE_LAB,  STRUCTURE_ROAD],
]

export const FASTFILLER_STAMP: Stamp = [
  [undefined,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      undefined],
  [STRUCTURE_ROAD, STRUCTURE_EXTENSION, STRUCTURE_EXTENSION, STRUCTURE_EXTENSION, STRUCTURE_EXTENSION, STRUCTURE_EXTENSION, STRUCTURE_ROAD],
  [STRUCTURE_ROAD, STRUCTURE_SPAWN,     undefined,           STRUCTURE_EXTENSION, undefined,           STRUCTURE_SPAWN,     STRUCTURE_ROAD],
  [STRUCTURE_ROAD, STRUCTURE_CONTAINER, STRUCTURE_EXTENSION, STRUCTURE_LINK,      STRUCTURE_EXTENSION, STRUCTURE_CONTAINER, STRUCTURE_ROAD],
  [STRUCTURE_ROAD, STRUCTURE_EXTENSION, undefined,           STRUCTURE_EXTENSION, undefined,           STRUCTURE_EXTENSION, STRUCTURE_ROAD],
  [STRUCTURE_ROAD, STRUCTURE_EXTENSION, STRUCTURE_EXTENSION, STRUCTURE_SPAWN,     STRUCTURE_EXTENSION, STRUCTURE_EXTENSION, STRUCTURE_ROAD],
  [undefined,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      STRUCTURE_ROAD,      undefined],
]
