{
 "title": "Overview",
 "tags": [ "screeps" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "office", "query": "stats.gauges.offices.*" }
  ]
 },
 "panels": [
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.cpu.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(stats.gauges.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.cpu.bucket" }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(stats.gauges.time), 'Ticks Per Update')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.profiling.*)"
    }
   ]
  },
  {
   "title": "Creeps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.creepCount" }
   ]
  },
  {
   "title": "Offices",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.officeCount" }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.gcl.level" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(stats.gauges.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.gcl.progressTotal, #B), #C)"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), #B), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), #B), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Global Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.offices.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.offices.*.storageEnergy), 'Storage')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.offices.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")"
    }
   ]
  },
  { "title": "Office $office", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "office" },
  {
   "title": "RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.offices.$office.controllerLevel"
    }
   ]
  },
  {
   "title": "RCL progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(stats.gauges.offices.$office.controllerProgress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next RCL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.offices.$office.controllerProgressTotal, #B), #C)"
    }
   ]
  },
  {
   "title": "RCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.offices.$office.controllerProgress), #C), 'RCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.offices.$office.controllerProgress), #C), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.offices.$office.storageLevel, 'Storage level')"
    },
    {
     "target": "alias(stats.gauges.offices.$office.terminalLevel, 'Terminal level')"
    }
   ]
  },
  {
   "title": "Harvested Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.offices.$office.franchiseIncome, 'Energy Income')"
    },
    {
     "target": "alias(stats.gauges.offices.$office.logisticsThroughput, 'Logistics Throughput')"
    },
    {
     "target": "alias(movingAverage(stats.gauges.offices.$office.logisticsOutput, '10min'), 'Logistics Output')"
    }
   ]
  },
  {
   "title": "CPU Surplus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.offices.$office.missions.*.cpuAccuracy, 5)"
    }
   ]
  },
  {
   "title": "Energy Surplus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.offices.$office.missions.*.energyAccuracy, 5)"
    }
   ]
  },
  {
   "title": "Room Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(stats.gauges.offices.$office.energyAvailable, 'Spawns and Extensions')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(stats.gauges.offices.$office.storageEnergy, 'Storage'), alias(stats.gauges.offices.$office.energyAvailable, 'Spawns and Extensions'), alias(stats.gauges.offices.$office.terminalEnergy, 'Terminal')), \"Total\")"
    },
    {
     "target": "alias(stats.gauges.offices.$office.energyCapacityAvailable, 'Spawns and Extensions')"
    }
   ]
  },
  {
   "title": "Spawn Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(stats.gauges.offices.$office.spawnUptime, 'Spawn uptime')"
    }
   ]
  },
  {
   "title": "Running Missions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.offices.$office.missions.*.count, 5)"
    }
   ]
  }
 ]
}