export enum MinionTypes {
  ACCOUNTANT = 'ACCOUNTANT',
  CLERK = 'CLERK',
  ENGINEER = 'ENGINEER',
  PAVER = 'PAVER',
  FOREMAN = 'FOREMAN',
  GUARD = 'GUARD',
  AUDITOR = 'AUDITOR',
  LAWYER = 'LAWYER',
  RESEARCH = 'PARALEGAL',
  SALESMAN = 'SALESMAN',
  MARKETER = 'MARKETER',
  BLINKY = 'BLINKY',
  MEDIC = 'MEDIC',
  POWER_BANK_ATTACKER = 'PBA',
  POWER_BANK_HEALER = 'PBH',
  DISMANTLER = 'DISMANTLER'
}
