import { BARRIER_LEVEL } from "config";

export const RANGED_HEAL_RANGE = 3;
export const HEAL_RANGE = 1;
export const UPGRADE_CONTROLLER_COST = 1;

export const BUILD_COSTS_BY_RCL: Record<number, number> = {
    0: 0,
    1: CONSTRUCTION_COST[STRUCTURE_SPAWN],
    2: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 5) +
        (CONSTRUCTION_COST[STRUCTURE_CONTAINER] * 2),
    3: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 5) +
        CONSTRUCTION_COST[STRUCTURE_TOWER],
    4: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_STORAGE] +
        (BARRIER_LEVEL[4] * 20 * REPAIR_COST),
    5: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_TOWER] +
        (CONSTRUCTION_COST[STRUCTURE_LINK] * 2) +
        (BARRIER_LEVEL[5] - BARRIER_LEVEL[4] * 20 * REPAIR_COST),
    6: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_LINK] +
        CONSTRUCTION_COST[STRUCTURE_TERMINAL] +
        CONSTRUCTION_COST[STRUCTURE_EXTRACTOR] +
        CONSTRUCTION_COST[STRUCTURE_CONTAINER] +
        (CONSTRUCTION_COST[STRUCTURE_LAB] * 3) +
        (BARRIER_LEVEL[6] - BARRIER_LEVEL[5] * 20 * REPAIR_COST),
    7: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_SPAWN] +
        CONSTRUCTION_COST[STRUCTURE_TOWER] +
        (CONSTRUCTION_COST[STRUCTURE_LAB] * 3) +
        CONSTRUCTION_COST[STRUCTURE_FACTORY] +
        (BARRIER_LEVEL[7] - BARRIER_LEVEL[6] * 20 * REPAIR_COST),
    8: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_SPAWN] +
        (CONSTRUCTION_COST[STRUCTURE_TOWER] * 3) +
        (CONSTRUCTION_COST[STRUCTURE_LAB] * 4) +
        CONSTRUCTION_COST[STRUCTURE_POWER_SPAWN] +
        (BARRIER_LEVEL[8] - BARRIER_LEVEL[7] * 20 * REPAIR_COST),
}
