import { BARRIER_LEVEL } from "config";

export const RANGED_HEAL_RANGE = 3;
export const HEAL_RANGE = 1;
export const UPGRADE_CONTROLLER_COST = 1;

export const BUILD_COSTS_BY_RCL: Record<number, number> = {
    0: 0,
    1: CONSTRUCTION_COST[STRUCTURE_SPAWN],
    2: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 5) +
        (CONSTRUCTION_COST[STRUCTURE_CONTAINER] * 2),
    3: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 5) +
        CONSTRUCTION_COST[STRUCTURE_TOWER],
    4: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_STORAGE] +
        (BARRIER_LEVEL[4] * 20 * REPAIR_COST),
    5: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_TOWER] +
        (CONSTRUCTION_COST[STRUCTURE_LINK] * 2) +
        ((BARRIER_LEVEL[5] - BARRIER_LEVEL[4]) * 20 * REPAIR_COST),
    6: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_LINK] +
        CONSTRUCTION_COST[STRUCTURE_TERMINAL] +
        CONSTRUCTION_COST[STRUCTURE_EXTRACTOR] +
        CONSTRUCTION_COST[STRUCTURE_CONTAINER] +
        (CONSTRUCTION_COST[STRUCTURE_LAB] * 3) +
        ((BARRIER_LEVEL[6] - BARRIER_LEVEL[5]) * 20 * REPAIR_COST),
    7: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_SPAWN] +
        CONSTRUCTION_COST[STRUCTURE_TOWER] +
        (CONSTRUCTION_COST[STRUCTURE_LAB] * 3) +
        100000 + // CONSTRUCTION_COST[STRUCTURE_FACTORY] + // Constant doesn't work in private server?
        ((BARRIER_LEVEL[7] - BARRIER_LEVEL[6]) * 20 * REPAIR_COST),
    8: (CONSTRUCTION_COST[STRUCTURE_EXTENSION] * 10) +
        CONSTRUCTION_COST[STRUCTURE_SPAWN] +
        (CONSTRUCTION_COST[STRUCTURE_TOWER] * 3) +
        (CONSTRUCTION_COST[STRUCTURE_LAB] * 4) +
        CONSTRUCTION_COST[STRUCTURE_POWER_SPAWN] +
        ((BARRIER_LEVEL[8] - BARRIER_LEVEL[7]) * 20 * REPAIR_COST),
}

/**
 * From https://github.com/screepers/screeps-snippets/blob/master/src/globals/JavaScript/resourceColors.js
 */
export const RES_COLORS: Record<ResourceConstant, string> = {
    H: '#989898',
    O: '#989898',
    U: '#48C5E5',
    L: '#24D490',
    K: '#9269EC',
    Z: '#D9B478',
    X: '#F26D6F',
    energy: '#FEE476',
    battery: '#FEE476',
    power: '#F1243A',
    ops: '#F1243A',

    reductant: '#989898',
    oxidant: '#989898',
    utrium_bar: '#48C5E5',
    lemergium_bar: '#24D490',
    keanium_bar: '#9269EC',
    zynthium_bar: '#D9B478',
    purifier: '#F26D6F',

    OH: '#B4B4B4',
    ZK: '#B4B4B4',
    UL: '#B4B4B4',
    G: '#FFFFFF',

    ghodium_melt: '#FFFFFF',
    composite: '#FFFFFF',
    crystal: '#FFFFFF',
    liquid: '#FFFFFF',

    UH: '#50D7F9',
    UO: '#50D7F9',
    KH: '#A071FF',
    KO: '#A071FF',
    LH: '#00F4A2',
    LO: '#00F4A2',
    ZH: '#FDD388',
    ZO: '#FDD388',
    GH: '#FFFFFF',
    GO: '#FFFFFF',

    UH2O: '#50D7F9',
    UHO2: '#50D7F9',
    KH2O: '#A071FF',
    KHO2: '#A071FF',
    LH2O: '#00F4A2',
    LHO2: '#00F4A2',
    ZH2O: '#FDD388',
    ZHO2: '#FDD388',
    GH2O: '#FFFFFF',
    GHO2: '#FFFFFF',

    XUH2O: '#50D7F9',
    XUHO2: '#50D7F9',
    XKH2O: '#A071FF',
    XKHO2: '#A071FF',
    XLH2O: '#00F4A2',
    XLHO2: '#00F4A2',
    XZH2O: '#FDD388',
    XZHO2: '#FDD388',
    XGH2O: '#FFFFFF',
    XGHO2: '#FFFFFF',

    metal: '#956F5C',
    alloy: '#956F5C',
    tube: '#956F5C',
    fixtures: '#956F5C',
    frame: '#956F5C',
    hydraulics: '#956F5C',
    machine: '#956F5C',

    biomass: '#84B012',
    cell: '#84B012',
    phlegm: '#84B012',
    tissue: '#84B012',
    muscle: '#84B012',
    organoid: '#84B012',
    organism: '#84B012',

    silicon: '#4DA7E5',
    wire: '#4DA7E5',
    switch: '#4DA7E5',
    transistor: '#4DA7E5',
    microchip: '#4DA7E5',
    circuit: '#4DA7E5',
    device: '#4DA7E5',

    mist: '#DA6BF5',
    condensate: '#DA6BF5',
    concentrate: '#DA6BF5',
    extract: '#DA6BF5',
    spirit: '#DA6BF5',
    emanation: '#DA6BF5',
    essence: '#DA6BF5'
}

export const RESOURCE_INGREDIENTS: Record<MineralCompoundConstant, [ResourceConstant, ResourceConstant]> = {
    [RESOURCE_HYDROXIDE]: [RESOURCE_HYDROGEN, RESOURCE_OXYGEN],
    [RESOURCE_ZYNTHIUM_KEANITE]: [RESOURCE_ZYNTHIUM, RESOURCE_KEANIUM],
    [RESOURCE_UTRIUM_LEMERGITE]: [RESOURCE_UTRIUM, RESOURCE_LEMERGIUM],
    [RESOURCE_GHODIUM]: [RESOURCE_ZYNTHIUM_KEANITE, RESOURCE_UTRIUM_LEMERGITE],

    [RESOURCE_UTRIUM_HYDRIDE]: [RESOURCE_UTRIUM, RESOURCE_HYDROGEN],
    [RESOURCE_UTRIUM_OXIDE]: [RESOURCE_UTRIUM, RESOURCE_OXYGEN],
    [RESOURCE_KEANIUM_HYDRIDE]: [RESOURCE_KEANIUM, RESOURCE_HYDROGEN],
    [RESOURCE_KEANIUM_OXIDE]: [RESOURCE_KEANIUM, RESOURCE_OXYGEN],
    [RESOURCE_LEMERGIUM_HYDRIDE]: [RESOURCE_LEMERGIUM, RESOURCE_HYDROGEN],
    [RESOURCE_LEMERGIUM_OXIDE]: [RESOURCE_LEMERGIUM, RESOURCE_OXYGEN],
    [RESOURCE_ZYNTHIUM_HYDRIDE]: [RESOURCE_ZYNTHIUM, RESOURCE_HYDROGEN],
    [RESOURCE_ZYNTHIUM_OXIDE]: [RESOURCE_ZYNTHIUM, RESOURCE_OXYGEN],
    [RESOURCE_GHODIUM_HYDRIDE]: [RESOURCE_GHODIUM, RESOURCE_HYDROGEN],
    [RESOURCE_GHODIUM_OXIDE]: [RESOURCE_GHODIUM, RESOURCE_OXYGEN],

    [RESOURCE_UTRIUM_ACID]: [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_KEANIUM_ACID]: [RESOURCE_KEANIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_OXIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_GHODIUM_ACID]: [RESOURCE_GHODIUM_HYDRIDE, RESOURCE_HYDROXIDE],
    [RESOURCE_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_OXIDE, RESOURCE_HYDROXIDE],

    [RESOURCE_CATALYZED_UTRIUM_ACID]: [RESOURCE_UTRIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_UTRIUM_ALKALIDE]: [RESOURCE_UTRIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_KEANIUM_ACID]: [RESOURCE_KEANIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_KEANIUM_ALKALIDE]: [RESOURCE_KEANIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_LEMERGIUM_ACID]: [RESOURCE_LEMERGIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE]: [RESOURCE_LEMERGIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_ZYNTHIUM_ACID]: [RESOURCE_ZYNTHIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE]: [RESOURCE_ZYNTHIUM_ALKALIDE, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_GHODIUM_ACID]: [RESOURCE_GHODIUM_ACID, RESOURCE_CATALYST],
    [RESOURCE_CATALYZED_GHODIUM_ALKALIDE]: [RESOURCE_GHODIUM_ALKALIDE, RESOURCE_CATALYST],
}

export const MINERALS: ResourceConstant[] = [
    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN,
    RESOURCE_UTRIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_KEANIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST,
]
